require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '11.0'

pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

target 'example' do
  use_unimodules!(exclude:[
    'expo-constants', 
    'expo-file-system', 
    'expo-image-loader', 
    'expo-permissions', 
    'unimodules-app-loader', 
    'unimodules-barcode-scanner-interface', 
    'unimodules-camera-interface', 
    'unimodules-constants-interfac', 
    'unimodules-face-detector-interface', 
    'unimodules-file-system-interface', 
    'unimodules-font-interfac', 
    'unimodules-image-loader-interface', 
    'unimodules-permissions-interface', 
    'unimodules-sensors-interface', 
    'unimodules-task-manager-interface'
  ])
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
end
